name: Build APK
on:
  push:
    branches: [ main, master ]

jobs:
  build:
    # ИСПОЛЬЗУЕМ СТАРУЮ СТАБИЛЬНУЮ UBUNTU
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4

      # ИСПОЛЬЗУЕМ JAVA 11 (Критично для ошибки 100)
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
          python3-pip build-essential git python3 \
          python3-dev ffmpeg libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev \
          libsdl2-ttf-dev libportmidi-dev libswscale-dev libavformat-dev \
          libavcodec-dev zlib1g-dev libgstreamer1.0 gstreamer1.0-plugins-base \
          gstreamer1.0-plugins-good unzip autoconf libtool pkg-config \
          libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev zip

      - name: Install Buildozer
        run: |
          pip3 install --upgrade pip
          pip3 install --upgrade buildozer cython virtualenv

      # Запуск без "yes |", так как мы добавили accept_license в spec файл
      - name: Build APK
        run: buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: BombusPro
          path: bin/*.apk
